
language: python

python: 2.7

sudo: false

cache:
  directories:
  - eggs
  - parts/node

install:
- python bootstrap.py
- bin/buildout annotate
- bin/buildout

script:
- bin/code-analysis
- bin/test

after_success:
- bin/createcoverage
- pip install -q coveralls
- coveralls